"""Type stubs for the maturin-built Rust extension (chunk_your_skills._native)."""

from __future__ import annotations

from typing import Any

class ReconstructOptions:
    def __init__(self, *, keep_all_headers: bool = False) -> None: ...
    keep_all_headers: bool

class SkillsBuilder:
    def __init__(self, memory_only: bool = ..., output_dir: str | None = ...) -> None: ...
    def build_from_dirs(self, skill_dirs: list[str], config: dict[str, Any] | None = ...) -> dict[str, Any]: ...
    def build_from_file(self, source_path: str, config: dict[str, Any] | None = ...) -> dict[str, Any]: ...
    def write_catalog(self) -> dict[str, Any]: ...
    def to_skills_index_json(self) -> dict[str, Any]: ...
    def to_skills_dict(self) -> dict[str, Any]: ...

def build_page_index_for_file(source: str, config: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def build_page_index_only(skill_dirs: list[str], config: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def build_skills_index(skill_dirs: list[str], config: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def finalize_skill_document_json(
    entry_dir: str,
    doc_id: str,
    *,
    pipeline: str,
    index_params: dict[str, Any] | None,
    source_path: str,
    content_sha256: str | None = ...,
    built_at: str | None = ...,
) -> dict[str, Any]: ...
def get_skill_content_retrieve_result(
    index_or_docs: dict[str, Any] | list[Any],
    doc_id: str,
    line_num_specs: list[str] | None = ...,
    node_id_specs: list[str] | None = ...,
    options: ReconstructOptions | dict[str, Any] | None = ...,
) -> dict[str, Any]: ...
def get_skill_document(documents: dict[str, Any], doc_id: str) -> dict[str, Any]: ...
def get_skill_line_content(
    index_or_docs: dict[str, Any] | list[Any],
    doc_id: str,
    line_num_specs: list[str] | None = ...,
    node_id_specs: list[str] | None = ...,
) -> list[dict[str, Any]]: ...
def get_skill_line_content_from_spec(
    index_or_docs: dict[str, Any] | list[Any],
    doc_id: str,
    line_num_spec: str,
) -> list[dict[str, Any]]: ...
def get_skill_structure(documents: dict[str, Any], doc_id: str) -> Any: ...
def load_merged_skill_document_json(entry_dir: str, doc_id: str) -> dict[str, Any]: ...
def load_skills_index_from_dir(catalog_dir: str) -> dict[str, Any]: ...
def load_skills_index_from_entry(entry_dir: str, doc_id: str) -> dict[str, Any]: ...
def md_to_tree(markdown: str, source_path: str, config: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def page_index_valid(entry_dir: str, content_sha256: str) -> bool: ...
def parse_skill_node_ids(spec: str) -> list[int]: ...
def reconstruct_skill_markdown(
    index_or_docs: dict[str, Any] | list[Any],
    doc_id: str,
    line_num_specs: list[str] | None = ...,
    node_id_specs: list[str] | None = ...,
    options: ReconstructOptions | dict[str, Any] | None = ...,
) -> dict[str, Any]: ...
def repair_skill_nodes(entry_dir: str, doc_id: str, config: dict[str, Any] | None = ...) -> None: ...
def skills_index_from_decomposed_dir(dir_path: str) -> dict[str, Any]: ...
def token_count_from_decomposed_frontmatter(content: str) -> int | None: ...
def parse_frontmatter_fields(content: str) -> list[dict[str, Any]] | None: ...
def frontmatter_field(content: str, key: str) -> Any: ...
def update_skill_document_source_path(entry_dir: str, doc_id: str, source_path: str) -> dict[str, Any]: ...
def write_reconstructed_skill(
    catalog_dir: str,
    index_or_docs: dict[str, Any] | list[Any],
    doc_id: str,
    line_num_specs: list[str] | None = ...,
    node_id_specs: list[str] | None = ...,
    options: ReconstructOptions | dict[str, Any] | None = ...,
) -> str: ...
def write_skills_index(index: dict[str, Any], output_dir: str) -> None: ...
def ensure_skills_registry(
    source_paths: list[str] | list[dict[str, str]],
    catalog_root: str,
    pageindex_config: dict[str, Any] | None,
    policy: str = ...,
) -> list[dict[str, Any]]: ...
def configure_memory_cache(config: dict[str, Any]) -> None: ...
def get_version() -> str: ...
